In [2]:
import numpy as np

In [6]:
data1 = np.array([1,2,3,4,5])
data2 = np.array([[1,2,3],
                  [4,5,6]]
                )

In [7]:
data1.ndim, data2.ndim

(1, 2)

In [8]:
data1.shape

(5,)

In [9]:
data2.shape

(2, 3)

In [11]:
arr = np.array([[1,2,3],
                [4,5,6]]
                )
new_arr = arr.T
new_arr
new_arr.shape

(3, 2)

In [12]:
np.random.rand(5)

array([0.65460838, 0.62470155, 0.34308326, 0.13084075, 0.19913672])

In [13]:
np.random.randint(5,10,3)

array([6, 8, 6])

In [30]:
arr = np.arange(1,20,3)
arr_copy = arr.copy()
np.random.shuffle(arr_copy)
arr_copy

array([16, 13,  4,  7, 10, 19,  1])